//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NostroBank
    {
        public int ID { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> NostroLimit { get; set; }
        public string NostroDescription { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CurId { get; set; }
        public string NOSCode { get; set; }
        public string BankCode { get; set; }
    }
}
