//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterRECON
    {
        public long ID { get; set; }
        public long NostroBankId { get; set; }
        public Nullable<System.DateTime> LastStatementDate { get; set; }
        public string OurBooks { get; set; }
        public string TheirBooks { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public Nullable<decimal> EquivalentUSD { get; set; }
        public Nullable<decimal> LimitAvailable { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BR { get; set; }
        public int BID { get; set; }
        public int CurID { get; set; }
        public string Flag { get; set; }
    
        public virtual NostroBank NostroBank { get; set; }
    }
}
