//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterManualData
    {
        public long SNo { get; set; }
        public string DataType { get; set; }
        public Nullable<decimal> Inflow { get; set; }
        public Nullable<decimal> OutFlow { get; set; }
        public Nullable<decimal> NetBalance { get; set; }
        public Nullable<System.DateTime> DateFor { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> BR { get; set; }
        public int CurID { get; set; }
        public string Flag { get; set; }
    
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
