//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterCRRReportingCurrencyWise
    {
        public int SNo { get; set; }
        public Nullable<int> CRRID { get; set; }
        public string CCY { get; set; }
        public Nullable<int> CurID { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> CRRBal5PcrReq { get; set; }
        public Nullable<decimal> CRRBal10PcrReq { get; set; }
        public Nullable<decimal> EquivalentUSD { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> BR { get; set; }
        public Nullable<int> BID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Flag { get; set; }
    
        public virtual Branches Branch { get; set; }
        public virtual SBP_BlotterCRRReportFCY SBP_BlotterCRRReportFCY { get; set; }
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
