//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterImportExport
    {
        public int SNo { get; set; }
        public string BlotterType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BankCode { get; set; }
        public Nullable<int> CurId { get; set; }
        public string Branch { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> Inflow { get; set; }
        public Nullable<int> AgainstCurId { get; set; }
        public string AgainstBankCode { get; set; }
        public Nullable<decimal> Outflow { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Flag { get; set; }
        public Nullable<int> BID { get; set; }
        public Nullable<int> BR { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
