//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterCRRReportCalcSetup
    {
        public int ID { get; set; }
        public Nullable<int> CalcVal1 { get; set; }
        public Nullable<int> CalcVal2 { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int UserID { get; set; }
    
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
