//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterManualDeals
    {
        public int SNo { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public Nullable<decimal> InFlow { get; set; }
        public Nullable<decimal> OutFlow { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public string DealStatus { get; set; }
        public string Description { get; set; }
        public string BR { get; set; }
    }
}
