//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterFundingRepo
    {
        public long SNo { get; set; }
        public string DataType { get; set; }
        public string Bank { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<double> Rate { get; set; }
        public string DealType { get; set; }
        public string Broker { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public string IssueType { get; set; }
        public Nullable<decimal> InFlow { get; set; }
        public Nullable<decimal> OutFLow { get; set; }
        public string Note { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BR { get; set; }
        public int BID { get; set; }
        public int CurID { get; set; }
        public string Flag { get; set; }
    
        public virtual Branches Branch { get; set; }
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
