//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterClearing
    {
        public long SNo { get; set; }
        public int TTID { get; set; }
        public Nullable<System.DateTime> Clearing_Date { get; set; }
        public string ClearingCOde { get; set; }
        public Nullable<decimal> Clearing_InFlow { get; set; }
        public Nullable<decimal> AdjClearing_InFlow { get; set; }
        public Nullable<decimal> Clearing_OutFLow { get; set; }
        public Nullable<decimal> AdjClearing_OutFLow { get; set; }
        public string Note { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BR { get; set; }
        public int BID { get; set; }
        public int CurID { get; set; }
        public string Flag { get; set; }
    
        public virtual Branches Branch { get; set; }
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
