//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterDTL
    {
        public int SNo { get; set; }
        public System.DateTime DTL_Date { get; set; }
        public string DTL_Code { get; set; }
        public int NO_OF_Days { get; set; }
        public double DTL_Amount { get; set; }
        public string T_User_Id { get; set; }
        public System.DateTime T_Date { get; set; }
        public string Flag { get; set; }
        public string BR { get; set; }
    }
}
