//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterCRRFINCON
    {
        public long SNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> DemandTimeLiablities { get; set; }
        public Nullable<decimal> TimeLiablitiesOverOneYear { get; set; }
        public Nullable<decimal> DemandTimeLiablitiesTotal { get; set; }
        public Nullable<decimal> PreMatureDeposit { get; set; }
        public Nullable<decimal> DemandTimeLiablitiesTotalForCRR { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<decimal> ExtraBenefits { get; set; }
        public Nullable<decimal> CRR1Requirement { get; set; }
        public Nullable<decimal> CRR2Requirement { get; set; }
        public Nullable<decimal> RequirementPenalty { get; set; }
        public Nullable<decimal> RequirementExtBenefit { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BR { get; set; }
        public int BID { get; set; }
        public int CurID { get; set; }
        public string Flag { get; set; }
    
        public virtual Branches Branch { get; set; }
        public virtual SBP_LoginInfo SBP_LoginInfo { get; set; }
    }
}
