//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterDTLDaysWiseBal
    {
        public int Id { get; set; }
        public int DTL_Days { get; set; }
        public System.DateTime DTL_Date { get; set; }
        public System.DateTime NextDate { get; set; }
        public Nullable<decimal> DTL_Amount { get; set; }
        public Nullable<decimal> MinAmount_3P { get; set; }
        public Nullable<decimal> MaxAmount_5P { get; set; }
        public Nullable<decimal> Friday_01 { get; set; }
        public System.DateTime Date_01 { get; set; }
        public Nullable<decimal> CashFlow_01 { get; set; }
        public Nullable<decimal> CashOutFlow_01 { get; set; }
        public Nullable<decimal> Saturday_02 { get; set; }
        public System.DateTime Date_02 { get; set; }
        public Nullable<decimal> CashFlow_02 { get; set; }
        public Nullable<decimal> CashOutFlow_02 { get; set; }
        public Nullable<decimal> Sunday_03 { get; set; }
        public System.DateTime Date_03 { get; set; }
        public Nullable<decimal> CashFlow_03 { get; set; }
        public Nullable<decimal> CashOutFlow_03 { get; set; }
        public Nullable<decimal> Monday_04 { get; set; }
        public System.DateTime Date_04 { get; set; }
        public Nullable<decimal> CashFlow_04 { get; set; }
        public Nullable<decimal> CashOutFlow_04 { get; set; }
        public Nullable<decimal> Tuesday_05 { get; set; }
        public System.DateTime Date_05 { get; set; }
        public Nullable<decimal> CashFlow_05 { get; set; }
        public Nullable<decimal> CashOutFlow_05 { get; set; }
        public Nullable<decimal> Wednesday_06 { get; set; }
        public System.DateTime Date_06 { get; set; }
        public Nullable<decimal> CashFlow_06 { get; set; }
        public Nullable<decimal> CashOutFlow_06 { get; set; }
        public Nullable<decimal> Thursday_07 { get; set; }
        public System.DateTime Date_07 { get; set; }
        public Nullable<decimal> CashFlow_07 { get; set; }
        public Nullable<decimal> CashOutFlow_07 { get; set; }
        public Nullable<decimal> Friday_08 { get; set; }
        public System.DateTime Date_08 { get; set; }
        public Nullable<decimal> CashFlow_08 { get; set; }
        public Nullable<decimal> CashOutFlow_08 { get; set; }
        public Nullable<decimal> Saturday_09 { get; set; }
        public System.DateTime Date_09 { get; set; }
        public Nullable<decimal> CashFlow_09 { get; set; }
        public Nullable<decimal> CashOutFlow_09 { get; set; }
        public Nullable<decimal> Sunday_10 { get; set; }
        public System.DateTime Date_10 { get; set; }
        public Nullable<decimal> CashFlow_10 { get; set; }
        public Nullable<decimal> CashOutFlow_10 { get; set; }
        public Nullable<decimal> Monday_11 { get; set; }
        public System.DateTime Date_11 { get; set; }
        public Nullable<decimal> CashFlow_11 { get; set; }
        public Nullable<decimal> CashOutFlow_11 { get; set; }
        public Nullable<decimal> Tuesday_12 { get; set; }
        public System.DateTime Date_12 { get; set; }
        public Nullable<decimal> CashFlow_12 { get; set; }
        public Nullable<decimal> CashOutFlow_12 { get; set; }
        public Nullable<decimal> Wednesday_13 { get; set; }
        public System.DateTime Date_13 { get; set; }
        public Nullable<decimal> CashFlow_13 { get; set; }
        public Nullable<decimal> CashOutFlow_13 { get; set; }
        public Nullable<decimal> Thursday_14 { get; set; }
        public System.DateTime Date_14 { get; set; }
        public Nullable<decimal> CashFlow_14 { get; set; }
        public Nullable<decimal> CashOutFlow_14 { get; set; }
        public string BR { get; set; }
    }
}
