//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBP_BlotterOpeningClosingBalanceDIfferential
    {
        public long SNo { get; set; }
        public long OpenBalID { get; set; }
        public string DataType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> InFlow { get; set; }
        public Nullable<decimal> OutFLow { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BR { get; set; }
        public int CurID { get; set; }
        public string Flag { get; set; }
    
        public virtual SBP_BlotterOpeningBalance SBP_BlotterOpeningBalance { get; set; }
    }
}
