//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPageRelation
    {
        public int UPRID { get; set; }
        public int URID { get; set; }
        public int WPID { get; set; }
        public Nullable<bool> DateChangeAccess { get; set; }
        public Nullable<bool> EditAccess { get; set; }
        public Nullable<bool> DeleteAccess { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual WebPages WebPage { get; set; }
    }
}
