//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OPICSM2M
    {
        public string br { get; set; }
        public string prodcode { get; set; }
        public string dealno { get; set; }
        public string sn { get; set; }
        public Nullable<System.DateTime> dealdate { get; set; }
        public Nullable<System.DateTime> vdate { get; set; }
        public Nullable<int> days { get; set; }
        public string ps { get; set; }
        public string ccy { get; set; }
        public Nullable<decimal> ccynet { get; set; }
        public Nullable<decimal> dealrate { get; set; }
        public string ctrccy { get; set; }
        public Nullable<decimal> ctrnet { get; set; }
        public double revlcyamt { get; set; }
        public Nullable<System.DateTime> currdate { get; set; }
        public Nullable<System.DateTime> olddate { get; set; }
        public double InterPRateOld { get; set; }
        public double InterPRate { get; set; }
        public Nullable<double> plsold { get; set; }
        public Nullable<double> pls { get; set; }
    }
}
